# Generated by Django 5.0.3 on 2024-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('course', models.CharField(choices=[('math', 'Mathematics'), ('sci', 'Science'), ('eng', 'English'), ('hist', 'History'), ('geo', 'Geography'), ('lang', 'Language Arts'), ('art', 'Art'), ('music', 'Music'), ('comp', 'Computer Science'), ('pe', 'Physical Education')], max_length=50)),
            ],
        ),
    ]
